### ISSUE TITLE
Component Extensions are limited in nature

### ISSUE THREAD

**Issue by EncodedVenom** [Sleitnick/RbxUtil#10]
Component Extensions can only hook into lifecycle events to a component.
While this is nice for creating a component janitor and destroying it when you no longer need the component, it can also restrict what extensions could be. I'm proposing that extensions should be able to hook more deeply into the process. Being able to reject or otherwise prevent component creation would allow for RequiredComponents (from the old V1 module), something which is quite a task with only lifecycle hooks, and more creative ideas.

**Comment by Sleitnick** [comment]
That's pretty interesting. I wonder if there could be a preflight method such as `ShouldCreate` or something that, if present, has to return `true|false`. Any `false` value would stop the component from being created. It might be too dangerous to do anything else, such as `ShouldDestroy` or something. But I do really like the idea of being able to control if the component should be created or not.

**Comment by EncodedVenom** [comment]
It seems work is being done on this with #15.
