### ISSUE TITLE
Trove occasionally fails to cleanup at least one object once it cleans a promise

### ISSUE THREAD

**Issue by mvyasu** [Sleitnick/RbxUtil#108]
Over the past month I've noticed that after converting old code to use Trove instead of Janitor there were certain scenarios where not all objects in a trove were properly cleaned. It always seemed to involve a promise and I just assumed I was doing something wrong. 

However, after a bit of digging tonight, I discovered that Trove occasionally fails to cleanup an object once it cleans a promise added through `Trove:AddPromise()`. Apparently when a promise is cleaned up, it removes the itself from the `Trove._objects` array, shifting all the proceeding objects, causing the in pairs loop inside `Trove:Clean()` to skip at least one object if there is one.

It's really easy to reproduce this issue:

```lua
local trove = Trove.new()

trove:AddPromise(Promise.delay(5)):finallyCall(print, "Promise cleaned!")
trove:Add(function() print("Fn 1 cleaned!") end)
trove:Add(function() print("Fn 2 cleaned!") end)
trove:Clean()

--> Promise cleaned!
--> Fn 1 cleaned!
```

**Comment by Sleitnick** [comment]
Good catch! I'll fix that right away.

**Comment by Sleitnick** [comment]
Trove `v0.5.0` has the fix
