### ISSUE TITLE
Component doesn't remove ancestryChangedHandle from the component class' trove when an instance is untagged

### ISSUE THREAD

**Issue by mvyasu** [Sleitnick/RbxUtil#116]
Right now there's a minor memory leak with the Component module. When an instance is untagged, it will disconnect the `ancestryChangeHandle` connection and remove it from `watchingInstances`, but not from the component class' trove. To fix this, InstanceUntagged should be something along these lines:

```lua
local function InstanceUntagged(instance: Instance)
	local watchHandle = watchingInstances[instance]
	watchingInstances[instance] = nil
	
	self[KEY_TROVE]:Remove(watchHandle)
	
	TryDeconstructComponent(instance)
end
```

You can kill two birds with one stone by using Trove:Remove() to disconnect the connection and to remove its reference from the component class' trove.

**Comment by Sleitnick** [comment]
Sorry for the exactly 1-year delay on this. Looking into this now.
