### ISSUE TITLE
TableUtil.Map() documentation issue

### ISSUE THREAD

**Issue by 4812571** [Sleitnick/RbxUtil#117]
TableUtil's documentation shows an example of TableUtil.map() taking in a predicate of form (key, value) -> nil. However, TableUtil'
s code, and documentation states that the predicate is (value, key, tab) -> nil.

The following code from the documentation is incorrect:
```lua
local t = {A = 10, B = 20, C = 30}
local t2 = TableUtil.Map(t, function(key, value)
	return value * 2
end)
print(t2) --> {A = 20, B = 40, C = 60}
```

The code should read:

```lua
local t = {A = 10, B = 20, C = 30}
local t2 = TableUtil.Map(t, function(value)
	return value * 2
end)
print(t2) --> {A = 20, B = 40, C = 60
```

**Comment by Sleitnick** [comment]
Thanks!
