### ISSUE TITLE
Add RemoteProperty to Comm

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/RbxUtil#16]
Add a RemoteProperty to Comm, for both the server and client.

Possible API:

Server:
- `RemoteProperty.new(defaultValue: any)`
- `rp:SetAll(value: any)`
- `rp:Get(player: Player?): any`
- `rp:Set(player: Player, value: any)`
- `rp:Clear(player: Player)`
- `rp:ClearAll()`

Client:
- `ClientRemoteProperty.new()`
- `rp:Get(): any`
- `rp.Changed: Signal<any>`

**Comment by nottirb** [comment]
It would be nice if, for tables, rather than just sending the entire table over the network, it instead detects table changes and sends that instead. Just a thought!
