### ISSUE TITLE
Mouse should have a Moved() signal

### ISSUE THREAD

**Issue by Rocky28447** [Sleitnick/RbxUtil#161]
The mouse input capturer should include a `Moved()` signal. Preferably this signal should be fired with how much the mouse moved by (newPosition - lastPosition).

**Comment by Sleitnick** [comment]
Added in Input@v2.2.0. To stay consistent with Roblox's APIs, the `Moved` event just passes the current position of the mouse. This allows the module to stay stateless. If the mouse is locked, the `GetDelta()` method can be used to get the change in position each frame.

To get the delta movement with a non-locked mouse, I recommend just adding some code outside of the mouse object to hold positional state:

```lua
local mouse = Mouse.new()

local lastPosition = mouse:GetPosition()

RunService.Heartbeat:Connect(function()
   local position = mouse:GetPosition()
   local delta = position - lastPosition
   lastPosition = position
   -- do something with `delta`
end)
```
