### ISSUE TITLE
Signal: Wait doesn't get canceled out on DisconnectAll or Destroy

### ISSUE THREAD

**Issue by VoidedBlades** [Sleitnick/RbxUtil#163]
When executing Signal:Wait() it yields the thread, however this yield is not canceled out on Destroy or DisconnectAll meaning you're left to manually resume the thread as a solution, granted you catch it and it wont turn into a memory leak. 
I feel like it's better to build this into Destroy/DisconnectAll.

Small reproduction, as obvious as it sounds.
```lua
local newSignal = Signal.new()
task.delay(1, function()
   newSignal:Destroy()
end)

print("waiting") -- prints
newSignal:Wait()
print("no longer waiting") -- doesn't ever print
```

**Comment by Sleitnick** [comment]
This is an interesting problem, because the question might be: _what_ should happen? Simply resuming the yielded thread would be a mistake, because the event hasn't happened. Perhaps the thread should just be cancelled/closed entirely?

**Comment by Sleitnick** [comment]
Further thoughts on canceling/closing vs. doing nothing:

The intent of the consuming code calling `:Wait()` is to indefinitely yield until the event occurs. Thus, if the event never occurs, it makes sense that the consumer thread never resumes. So I feel like closing the thread makes most sense?

**Comment by VoidedBlades** [comment]
I feel like canceling might be the best route to go, it does make the most sense out of all though I do feel like it could, depending on a user's setup, obstruct certain workflows.

E.g. waiting for a value and doing something with that value if any or none are returned to furthermore return things depending on the result.

I feel like it might be best to leave it up to the developer to handle disposal cases afterwards and resume the yielded thread?
Perhaps its worth looking at how roblox handles it with their waits as i've not yet checked anything in that regard after disposal (if they do anything at all with it that is)

**Comment by EmeraldSlash** [comment]
I would cancel by default since that is the most graceful kind of failure. However, that does leave a hole which could be filled by an additional "safe wait" method which always resumes and which provides information about what scenario it is resuming in.

```
if signal:SafeWait() then 
   -- Signal was fired, do something.
else
   -- Signal was destroyed, do something else.
end
```

Having an explicit API like this makes it easy to write code which behaves predictably in non-trivial scenarios. And it means if usage code wants different behaviour, they can get it basically for free instead of having to do extra stuff to work around whatever behaviour you choose for the standard Wait.

**Comment by VoidedBlades** [comment]
Having checked how Roblox does it with their events/bindables, which is just indefinite yielding, doesn't seem to entirely help but does put in perspective that the developer has to do it themselves somehow. Wrapping this around into the signal package itself would be more convenient, thus going about it as @EmeraldSlash mentioned. 

A separate API for resume cases after wait, and cancel the thread on disposal at `:wait()` sounds like a viable and non intrusive solution?

**Comment by Sleitnick** [comment]
I'm thinking that the best route is to cancel the thread.

Regarding a separate API: I don't think this is really necessary. If code is calling `signal:Wait()`, then it is already agreeing to the contract that it is entering into an indefinite yield. If the signal never fires, it yields forever, which is expected. By proxy, if the signal is destroyed, then it is also never fired, thus also yielding forever. The contract remains the same: the calling code will yield indefinitely.

Some trivial wrapper code could be written to add a 'timeout' to the yield:

```lua
local function Wait(signal, timeout)
   local thread = coroutine.running()
   local waitThread, timeoutThread

   waitThread = task.spawn(function()
      local value = signal:Wait() -- would need redesigned to handle varargs
      task.spawn(thread, true, value)
   end)

   timeoutThread = task.delay(timeout, function()
      task.cancel(waitThread)
      task.spawn(thread, false)
   end)

   return coroutine.yield()
end

-- e.g.:
local success, value = Wait(someSignal, 10)
if success then
   ...
end
```

I think it is outside the scope of the signal implementation to add further APIs to handle this behavior.

**Comment by EmeraldSlash** [comment]
Having a timeout wrapper doesn't help here since it is functionally different. But I suppose if you really want destroy handling you can get that with how you use the signal i.e. you always fire before you destroy.

```lua
if Signal:Wait() then
   -- Do stuff.
end

-- When firing normally..
Signal:Fire(true, ...)

-- When destroying..
Signal:Fire(false, ...)
Signal:Destroy()
```

Which I'm not a huge fan of since it forces lots of code to be written in a more specific way and requires some ingenuity to come up with, but at least it doesn't add much extra code or complexity.

**Comment by Sleitnick** [comment]
PR: #164

This will keep track of threads that call `Wait()` and will cancel those threads when `DisconnectAll()` is called.

Because of the change in behavior, this will be a major version bump, `v2.0.0`.

-------

A few minor changes are also piggy-backing off of this PR:
- Remove `Connection.new` constructor and just inline the construction.
- When calling `FireDeferred`, ensure the connection is connected
- Call `table.freeze` on the returned class-level table

**Comment by VoidedBlades** [comment]
> Having a timeout wrapper doesn't help here since it is functionally different. But I suppose if you really want destroy handling you can get that with how you use the signal i.e. you always fire before you destroy.
> 
> ```lua
> if Signal:Wait() then
>    -- Do stuff.
> end
> 
> -- When firing normally
> Signal:Fire(true, ...)
> 
> -- When destroying
> Signal:Fire(false, ...)
> Signal:Destroy()
> ```
> 
> Which I'm not a huge fan of since it forces lots of code to be written in a more specific way and requires some ingenuity to come up with, but at least it doesn't add much extra code :)

Theoretically you should be fine by wrapping the wait up around in a function if you truly wish for a specific thread to continue after wait in order to still do some manual behavior,

```lua
local function YieldThread()
   -- behavior
   Signal:Wait()
   -- post signal behavior, not executed if no fire happens
   return true
end

task.delay(2, function()
   Signal:Destroy()
end)

if not YieldThread() then
-- do more
end
```
While it can be considered an ugly work around its probably a more friendly one (with the thread canceling in place in the newer version) than a new API or needing to manually handle each and every edge case on `:wait()`. Your code should still resume as desired from there on without really causing anything undesired to execute which is a plus honestly

**Comment by Sleitnick** [comment]
I've added a warning. If a signal has yielded threads when it's disconnected, each thread will throw a warning such as this:
```
signal disconnected; yielded thread is being cancelled
Path.To.Script.That.Called.Wait:105
```
