### ISSUE TITLE
Input: Incorrect return type listed for PreferredInput.Observe()

### ISSUE THREAD

**Issue by Rocky28447** [Sleitnick/RbxUtil#165]
The documentation lists the return type of `PreferredInput.Observe()` as `Connection` when in reality it is a `function`.

![image](https://github.com/Sleitnick/RbxUtil/assets/26193486/bc929237-be8c-4ba8-94c5-2bb3b5664fee)
![image](https://github.com/Sleitnick/RbxUtil/assets/26193486/4cdd0bc4-7486-4e9f-8779-5cb5b13b920b)

**Comment by Sleitnick** [comment]
Thanks! The fix is now live in Input v2.2.1
