### ISSUE TITLE
How to use Trove to cleanup promises

### ISSUE THREAD

**Issue by nick-yangzj** [Sleitnick/RbxUtil#20]
Hi Sleitnick, I learned about the Knit framework with your Knit Tutorial video, and I appreciate you writing the framework and sharing this great tutorial! I learned a lot from it.

I have a question. Now that using Trove, how can I cancel the delay event of a promise ?(about respawn the ball）I tried to add a dealy promise to Trove, but I was reminded that there was no cleanup function. I can record this promise into a variable and execute its cancel event when the script is destroyed. I wonder if it can be implemented in combination with Trove or something else

Thanks

**Comment by Azzla** [comment]
Hey nick-yangzj, I ran into a similar issue and resolved it with custom :GivePromise extension to Trove.  Here's what I wrote:

```
-- Trying to add promise support to Trove
function Trove:GivePromise(promise)
	if not promise:getStatus() == "Started" then
		return promise
	end

	local newPromise = promise:doneReturn(promise)

	-- bypass Trove defaults and set resolved promise as nil directly, similar to Maid
	local cleanupMethod = newPromise:finally(function()
		for i,obj in ipairs(self._objects) do
			if obj[1] == newPromise then
				self._objects[i] = nil
			end
		end
	end)
	
	self:Add(newPromise, cleanupMethod)

	return newPromise
end
```
This was designed for the latest version of evaera's roblox-lua-promise library.

Then you can implement this in the Arena component as shown in the video:
```
self._trove:GivePromise(Promise.delay(RESPAWN_BALL_TIME)):andThen(function()
    self:_spawnBall()
end)
```

This may or may not be safe code to use, I'm not experienced enough with memory management tools like Trove/Maid to be sure.  However, when destroying the trove (removing arena) it appears to clean everything up as normal and no errors are thrown.

@Sleitnick would you consider adding promise support for Trove?

**Comment by christopher-buss** [comment]
Janitor also supports the adding of promises, as seen [here](https://github.com/howmanysmall/Janitor/blob/538fe7ae5ebffca63f6c2d97460633f88157e5df/src/init.lua#L150) for another implementation

**Comment by Sleitnick** [comment]
The hard part is the necessity to include the Promise library. If this can be done _without_ needing to pull in the Promise module as a dependency, then I'm ok with adding it. Current implementations of handling promises in Maid and Janitor require the Promise module.
