### ISSUE TITLE
Camera Shake Sustain Getting Progressively Stronger

### ISSUE THREAD

**Issue by yaelvalle** [Sleitnick/RbxUtil#21]
![image](https://user-images.githubusercontent.com/36064214/147192905-88d776b2-1189-4672-b6dc-ba3fa2eb8663.png)

[![Image from Gyazo](https://i.gyazo.com/91d0ae65c738968dfb9bb343296421b7.gif)](https://gyazo.com/91d0ae65c738968dfb9bb343296421b7)

**Comment by Sleitnick** [comment]
Good catch! Thankfully it's a simple fix

**Comment by Sleitnick** [comment]
This is now fixed in v0.1.1

**Comment by yaelvalle** [comment]
Perfect thank you
