### ISSUE TITLE
Bug with components 

### ISSUE THREAD

**Issue by Vilbat** [Sleitnick/RbxUtil#32]
I've discovered some weird behavior with components that I believe is a bug. 

Let's say we have a component called "thing".
The construct method of the component includes a task.wait(1) (or some other synchronous function).
If we clone a part with that tag from replicated storage into workspace the construct method of "thing" will run twice.

I've uploaded an example here:
https://github.com/Vilbat/ComponentBug

Edit: The construct method also runs twice if the ShouldConstruct() method yields.

**Comment by Djboy08** [comment]
Not sure if related but sure sounds it. Also with components, when Start() is called and if you yield it, Stop() never gets called if the Tag is removed during the yield of Start()

**Comment by Vilbat** [comment]
The issue is present in the latest version(2.3.0) of the component module.
