### ISSUE TITLE
Add waitForInstance to Component

### ISSUE THREAD

**Issue by CaptinLetus** [Sleitnick/RbxUtil#40]
Currently, I find myself doing  `repeat task.wait() until Component.FromInstance() ` very often.  It would be nice if we had a `Component.WaitForInstance` method that returned a promise.

An example: `Component.WaitForInstance(instance, timeout):andThen(function (component) end)`

**Comment by Sleitnick** [comment]
This also highlights how weird FromInstance is. Why is it a static function? It might as well be a method on the component.
