### ISSUE TITLE
WaitForInstance waits indefinitely

### ISSUE THREAD

**Issue by christopher-buss** [Sleitnick/RbxUtil#47]
As far as I'm aware, and please correct me if I'm wrong, but the promise fromEvent created by `WaitForInstance` if the component class does not currently exist on the object will exist forever if the component class will never actually exist on the object.

A propsal for this could be to add an optional timeout (though the use of `Promise:timeout(),` which would add safety to the component as the event will resolve itself if the instance doesn't exist after a certain timeframe.

Another propsal could just be to issue a warning, much like the standard Roblox WaitForChild, that would let the developer know that there is a possible infinite wait on the obejct, so that the developer is at least warned that the class does not appear in a timely manor.

**Comment by Sleitnick** [comment]
Yeah I think adding a timeout makes sense. This could be the second argument of WaitForInstance. Would also have to define a default timeout (usually I would choose 60 seconds). Could look something like this maybe:

```lua
local DEFAULT_TIMEOUT = 60

...

function Component:WaitForInstance(instance: Instance, timeout: number?)
   -- simplified; just demonstrating timeout:
   return somePromiseThing:timeout(timeout or DEFAULT_TIMEOUT)
end
```

Would also want to add into the documentation that this has a 60-second default timeout. Feel free to tag this onto https://github.com/Sleitnick/RbxUtil/pull/48 if you want!

**Comment by Sleitnick** [comment]
For reference, the `wait-for` module has these default timeouts just like described. https://github.com/Sleitnick/RbxUtil/blob/main/modules/wait-for/init.lua

**Comment by christopher-buss** [comment]
Could there be a potential usecase where someone does not wish to have a timeout at all? I'm unsure if in reality that would be good practice, but it could be used as a listener event in theory on the chance that it ever gets parented. I guess in this case the user _could_ supply a really large number (like math.huge) to ensure that it never times out, but I'm unsure of the implications of giving the user an option to just not timeout.

I can't personally think of a good use for this really, but just thought I'd throw it out there as well.

**Comment by christopher-buss** [comment]
This was something that _could_ be done, though I think it could just overcomplicate the API and may just be worth not having the option for **not** timeing out.

`lua
function Component:WaitForInstance(instance: Instance, timeout: (number | boolean?))
	local componentInstance = self:FromInstance(instance)
	if componentInstance then
		return Promise.resolve(componentInstance)
	end
	local promise = Promise.fromEvent(self.Started, function(c)
		local match = c.Instance == instance
		if match then
			componentInstance = c
		end
		return match
	end):andThen(function()
		return componentInstance
	end)
	if timeout == false then
		return promise
	end
	timeout = if timeout == true or timeout == nil then DEFAULT_TIMEOUT else timeout
	return promise:timeout(timeout)
end`

It may not be entirely correct, I have not actually tested this, but the idea would be that if you did the following, then it would use the default.
`lua
MyComponent:WaitForInstance(workspace.SomeInstance):andThen(function(myComponentInstance)
`

The folowing would never timeout if the user so desired.
`lua
MyComponent:WaitForInstance(workspace.SomeInstance, false):andThen(function(myComponentInstance)
`

The following would timeout after the desired time
`lua
MyComponent:WaitForInstance(workspace.SomeInstance, 10):andThen(function(myComponentInstance)
`

**Comment by Sleitnick** [comment]
My only concern is that this makes the method more confusing to understand at an API level. I think it's reasonable to assume a default timeout and just add a large number otherwise.

For systems that are dealing with parts that might stream in/out, it's better to use the [Streamable](https://sleitnick.github.io/RbxUtil/api/Streamable/) module, which lets you observe instances within a parent.

**Comment by christopher-buss** [comment]
Yes this was my concern too, I just thought it as something to consider.

**Comment by Sleitnick** [comment]
Added it in the attached PR: https://github.com/Sleitnick/RbxUtil/pull/53
