### ISSUE TITLE
Change Trove:AttachToInstance to .Destroying

### ISSUE THREAD

**Issue by LuaRook** [Sleitnick/RbxUtil#62]
On March 7th, Roblox released ``Destroy()`` replication, and with that came the long awaited ``.Destroying`` event of which is a better alternative to ``.AncestryChanged`` as ``.AncestryChanged`` fires every time the instances ancestry changes and it's often a shot in the dark, whereas ``.Destroying`` ensures the instance is deleted.

Janitor (https://github.com/howmanysmall/Janitor) has already made the switch to ``.Destroying``
https://devforum.roblox.com/t/destroy-can-now-replicate-to-clients/1694890

**Comment by Sleitnick** [comment]
Merged in with https://github.com/Sleitnick/RbxUtil/pull/65
