### ISSUE TITLE
Cannot access modules like `PreferredInput` in the new version of Input (2.0.0)

### ISSUE THREAD

**Issue by bubshayz** [Sleitnick/RbxUtil#77]
Input recently got a new update where it changes how you should access it's modules. After installing the latest version of Input (`2.0.0`),  I cannot access it's modules like the way it is stated in the documentation to do so, e.g `local PreferredInput = require(packages.Input.PreferredInput)` *errors*.

This is because of how Wally structures installed packages. Since in the wally packages folder where all my installed packages are, the source code of the `Input` **package** module is as follows:

```lua
return require(script.Parent._Index["sleitnick_input@2.0.0"]["input"])
``` 

And since the Input module it self returns a `nil` value, I *can't* access the modules and I'm forced to use an older version of Input i.e `1.3.3`..

**Comment by Sleitnick** [comment]
Well that's pretty annoying, isn't it? The big push to make this change was so that types could be imported. Maybe I'll just have to throw all the types into the Input module itself and work from there. Dang. Thanks for opening the issue.

**Comment by Y1195** [comment]
This also applies to the Silo. I cannot access the Util or TableWatcher modules. I want to :Dispatch a nil value and I think I need Util.None for it to update the state correctly?

**Comment by bubshayz** [comment]
Issue has been solved, closing..
