### ISSUE TITLE
Would it be possible to check the length in table-util/Truncate?

### ISSUE THREAD

**Issue by zeux** [Sleitnick/RbxUtil#79]
Truncate currently uses table.move into a freshly created table:

```
local function Truncate(tbl: Table, len: number): Table
	return table.move(tbl, 1, len, 1, table.create(len))
end
```

When `len` is greater than or equal to the length of the table, this operation redundantly copies the data; more importantly, it does an out-of-range move (with `len > #tbl`). We're looking into possibly limiting `table.move` indices to be in range of 1..#table -- while we haven't finished analyzing the production data for the impact of this change, and aren't sure if we actually *want* to make this change, a large outlier responsible for ~90% of out of range moves is the use of table-util in a top Roblox game, so it would be great to see if this can be changed in table-util.

**Comment by Sleitnick** [comment]
For lengths equal to the table size (after clamping), I'll just use `table.clone` instead. Expected behavior is a new table regardless, so I don't want to just return the original.
