### ISSUE TITLE
Component.Auto not found in V2

### ISSUE THREAD

**Issue by galdomar** [Sleitnick/RbxUtil#8]
HI Sleitnick, I start using the knit framework and watch your very good "Knit Game Tutorial".
In the video the util Component V1 ha an Auto method, but in V2 I don't find it.
I create a Goal Component in this way:

```lua
local Goal = Component.new({
  Tag = "Goal"
})

function Goal:Construct()
  self._maid = Maid.new()
  print("Goal created")
  self._maid:GiveTask(function()
    print("Goal destroyed")
  end)
end

function Goal:Stop()
  self._maid:Destroy()
end

return Goal
```

The Goal component is correctly attached to the Goal instances, the problem is that when I add at runtime a new Goal instance with tag "Goal", the component is not automatically attached.

I discovered that if I create the instance on server the component is attached, on the client no. I think this is the right behaviour.

**Comment by Sleitnick** [comment]
Hello! Component V2 works a bit differently, and the modules just need to be required in order for it to work. The [Loader](https://sleitnick.github.io/RbxUtil/api/Loader/) module could be used to do it quickly using `Loader.LoadChildren(parentWhereComponentsLive)`.

Alternatively, you can just loop through and require them yourself:

```lua
for _,componentModule in ipairs(parentWhereComponentsLive:GetChildren()) do
	require(componentModule)
end
```
