### ISSUE TITLE
RbxUtil Needs a Zone Util

### ISSUE THREAD

**Issue by LuaRook** [Sleitnick/RbxUtil#86]
RbxUtil lacks any sort of Zone Util. In making a Zone Util, it'd be reassuring for many developers who rely on the utils provided by RbxUtil. Perhaps if a player is detected in a zone, it'll run a provided callback like ``PreferredInput``, or the user could connect to a signal. It'd also be nice to have Trove and even Component support in some form. An example of this util being used is different zones giving the player different lighting ambiance, so if a Zone is named blue, then it gives a blue tint to the players screen. A proposed name for this util is ``Region``.

**Comment by 4812571** [comment]
Zone is probably too large of a concept for RbxUtil, which is mostly smaller utility classes - the same way octo-tree isn’t in RbxUtil
