### ISSUE TITLE
Components destroyed during Start() don't properly cleanup

### ISSUE THREAD

**Issue by eAi** [Sleitnick/RbxUtil#91]
If you have a component that is destroyed before `Start()` finishes, `Stop()` is never called and the Heartbeat and other update functions are never unregistered.

This destruction can happen either by the object being destroyed, the tag being removed or the object being removed from the set of ancestors defined.

This requires Start to not immediately return.

The following code will trigger this bug in a fairly easy fashion, but there are a number of other ways this can happen - we've seen it where Start() is waiting for a Knit service to be available before continuing and having the object destroyed before it is.

```
function SomeComponent:Start()
    self.Instance:Destroy()
    RunService.Heartbeat:Wait()
end
```

I don't think it's unreasonable to say that `Start` should return immediately - but this should be documented if this is the case - and ideally detected if it isn't. Often this can be quite an invisible problem and can cause memory leaks. We only noticed this due to a fairly specific set of circumstances but I suspect it may occur invisibly for other users.

Alternatively, `TryDeconstructComponent` should be revised - perhaps it can wait for `Start` to complete - i.e. the system could track that a component is in the process of starting. This seems like the least-worst solution to this issue.

**Comment by bubshayz** [comment]
This seems bad, `Start` shouldn't yield at all because it is unexpected. These cases should be countered by component extensions instead (`Starting`), e.g retrieving Knit Services, etc.

**Comment by eAi** [comment]
We’ve been running with the PR version above for some months and it has resolved these issues. It would be nice if it was merged in! In my experience saying that a function “shouldn’t yield” is fine in principle but Roblox makes it very easy to write code that yields accidentally. With my fix above you don’t need to worry about this.

**Comment by bubshayz** [comment]
Sure. Waiting for components to start is not really a viable solution. Instead, a better solution would be to wrap the `Start` method in a new Luau thread and cancel that thread as soon as the component stops.

**Comment by eAi** [comment]
To add to this issue, there's a further issue where components are stopped the same frame they're started. This is because the start happens inside a task.defer. I've also fixed this in my PR with a small change.

**Comment by eAi** [comment]
> Sure. Waiting for components to start is not really a viable solution. Instead, a better solution would be to wrap the `Start` method in a new Luau thread and cancel that thread as soon as the component stops.
Why do you think this isn't a viable solution? Don't luau threads have quite a lot of limitations on the API they can access? This would limit the functionality of components.

**Comment by Sleitnick** [comment]
I've created a PR for this @eAi. Sorry for the long delay.

In my PR, I am doing something similar to what @bubshayz is saying, where the startup procedure's thread is tracked and cancelled if needed. This handles the following scenarios:

- Component is stopped while Start method is still running (i.e. in a yielded state)
- Component's Start method triggers the component to stop (e.g. destroying the instance or removing the tag)

That second scenario is a bit tricky, as the thread is technically in a "normal" state which cannot be cancelled. The solution is to simply defer the cancellation.
